name: Publish

on:
  push:
    branches: main

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          
      - name: Setup .NET
        uses: actions/setup-dotnet@v1.8.0
        with:
          dotnet-version: 6.0.x
      
      - name: Install dependencies
        run: dotnet restore
        working-directory: src/MolangSharp.Tests
        
      - name: Build
        run: dotnet build --configuration Release --no-restore
        working-directory: src/MolangSharp.Tests
        
      - name: Test
        run: dotnet test --no-restore --verbosity normal
        working-directory: src/MolangSharp.Tests
    
  nuget:
    name: Publish to NuGET
    runs-on: ubuntu-latest
    needs: [test]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        fetch-depth: 0
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v1.8.0
      with:
        dotnet-version: 6.0.x
        
    - name: Install dependencies
      run: dotnet restore src/MolangSharp/MolangSharp.csproj
        
    - name: Build
      run: dotnet build --configuration Release --no-restore src/MolangSharp/MolangSharp.csproj

    - name: Publish
      run: |
        dotnet pack -c Release /p:PackageVersion=$(date +%Y.%m.%d.%H%M%S) src/MolangSharp/MolangSharp.csproj -o .
        dotnet nuget push *.nupkg -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_PUBLISH_KEY}} --skip-duplicate
