name: Publish

on:
  push:
    branches: main

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          
      - name: Setup .NET
        uses: actions/setup-dotnet@v1.8.0
        with:
          dotnet-version: 6.0.x
      
      - name: Install dependencies
        run: dotnet restore
        working-directory: src/Alex.MoLang.Tests
        
      - name: Build
        run: dotnet build --configuration Release --no-restore
        working-directory: src/Alex.MoLang.Tests
        
      - name: Test
        run: dotnet test --no-restore --verbosity normal
        working-directory: src/Alex.MoLang.Tests
    
  nuget:
    name: Publish to NuGET
    runs-on: ubuntu-latest
    needs: [test]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        fetch-depth: 0
      
    - uses: paulhatch/semantic-version@v4.0.2
      name: Generate version number
      id: version
      with:
        bump_each_commit: true
        change_path: "src"
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v1.8.0
      if: ${{ success() && steps.version.outputs.changed }}
      with:
        dotnet-version: 6.0.x
        
    - name: Install dependencies
      if: ${{ success() && steps.version.outputs.changed }}
      run: dotnet restore src/Alex.MoLang/Alex.MoLang.csproj
        
    - name: Build
      if: ${{ success() && steps.version.outputs.changed }}
      run: dotnet build --configuration Release --no-restore /p:Version="${{steps.version.outputs.version}}" src/Alex.MoLang/Alex.MoLang.csproj

    - name: Publish
      if: ${{ success() && steps.version.outputs.changed }}
      run: |
        dotnet pack -c Release /p:PackageVersion="${{steps.version.outputs.version}}" /p:Version="${{steps.version.outputs.version}}" src/Alex.MoLang/Alex.MoLang.csproj -o .
        dotnet nuget push *.nupkg -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_PUBLISH_KEY}} --skip-duplicate
